baseURL                = "https://techgaoshou.com/"
title                  = "高手科技"
defaultContentLanguage = "zh-cn"
hasCJKLanguage         = true
theme                  = "stack"

enableRobotsTXT = true
enableEmoji     = true

[pagination]
    pagerSize = 10

[permalinks]
    post = "/p/:slug/"
    page = "/:slug/"

[outputs]
    home = ["HTML", "RSS"]
