[[main]]
    identifier = "home"
    name       = "首页"
    url        = "/"
    weight     = 1
    [main.params]
        icon = "home"

[[main]]
    identifier = "overseas"
    name       = "出海系列"
    url        = "/categories/出海系列/"
    weight     = 2
    [main.params]
        icon = "language"

[[main]]
    identifier = "about"
    name       = "关于"
    url        = "/about/"
    weight     = 7
    [main.params]
        icon = "user"
