[[main]]
    identifier = "home"
    name       = "网站首页"
    url        = "/"
    weight     = 1
    [main.params]
        icon = "home"

[[main]]
    identifier = "overseas"
    name       = "玩转海外"
    url        = "/categories/玩转海外/"
    weight     = 2
    [main.params]
        icon = "plane"

[[main]]
    identifier = "about"
    name       = "关于作者"
    url        = "/about/"
    weight     = 7
    [main.params]
        icon = "user"
