mainSections   = ["post"]
rssFullContent = true
favicon        = "img/avatar.png"

[footer]
    since = 2025

[sidebar]
    subtitle = "出海 · AI · 美股 · 加密货币"
    avatar   = "img/avatar.png"

[article]
    math            = false
    toc             = true
    readingTime     = true
    [article.license]
        enabled = false

[comments]
    enabled = false

[widgets]
    homepage = [
        { type = "search" },
        { type = "archives", params = { limit = 5 } },
        { type = "categories", params = { limit = 10 } },
        { type = "tag-cloud", params = { limit = 10 } },
    ]
    page = [{ type = "toc" }]

[colorScheme]
    toggle  = true
    default = "auto"

[imageProcessing]
    [imageProcessing.cover]
        enabled = true
    [imageProcessing.content]
        enabled = true
